.TH tuxedo-tomte 1
.SH "NAME"
tuxedo-tomte \- Verwaltet Lösungen für TUXEDO Notebooks
.SH "ÜBERSICHT"
\fBtuxedo-tomte\fR <BEFEHL> [NAME...]
.PP
\fBtomte\fR <BEFEHL> [NAME...]
.SH "BESCHREIBUNG"
.PP
.I tuxedo-tomte
ist ein kleiner Helfer, der Aktualisierungen und Lösungen für
.B TUXEDO
Geräte im Hintergrund verwaltet\&.
Er gibt keine Informationen, Telemetrie oder ähnliche Informationen weiter.
.P
Viele, aber nicht alle Optionen benötigen Administrationsrechte\&.
.SH "OPTIONEN"
.PP
Folgende Optionen sind verfügbar:
.PP 
\fBlist\fR
.RS 4
Listet alle verfügbaren Optionen auf mit Name, Versionsnummer und ob diese aktiv,
blockiert oder für das System notwendig sind\&.
.RE
.PP 
\fBstatus\fR
.RS 4
Das gleiche wie 'list'\&.
.RE
.PP 
\fBversions\fR
.RS 4
Listet alle verfügbaren Optionen auf mit Name, Versionsnummer des Pakets (wenn
möglich), Versionsnummer des Moduls und ob diese aktiv,
blockiert oder für das System notwendig sind\&.
.RE

.PP
\fBdescription \fR\fI<MODUL>\fR
.RS 4
Zeigt eine kurze Beschreibung für dieses Modul\&.
.RE
.PP
\fBconfigure \fI<MODUL>\fR|\fIall\fR
.RS 4
Konfiguriert, wenn möglich das genannte Modul oder Lösung\&.
Das bedeutet, wenn es nicht bereits installiert oder blockiert ist und für
dieses System funktioniert\&.
.P
Falls \fBall\fR verwendet wird, werden alle Lösungen die für dieses System
existieren, installiert\&.
.P
Installierbare Module können mit
.IP
tomte list
.LP
angezeigt werden\&.
.P
Wenn \fBDONT_CONFIGURE\fR aktiv ist, werden keine Änderungen vorgenommen\&.
.P
Benötigt Administrationsrechte\&.
.RE
.PP
\fBreconfigure \fI<MODUL>\fR|\fIall\fR
.RS 4
Konfiguriert das genannte Modul oder die Lösung, auch wenn diese bereits
installiert war\&.
.P
Wenn das Modul blockiert oder nicht für dieses System konzipiert wurde,
werden keine Änderungen vorgenommen\&.
.P
Wenn \fBall\fR verwendet wird, werden alle Lösungen installiert die möglich
sind\&.
.P
Installierbare Module können mit
.IP
\fBtomte \fBlist\fR
.LP
angezeigt werden\&.
.P
Wenn \fBDONT_CONFIGURE\fR aktiv ist, werden keine Änderungen vorgenommen\&.
.P
Benötigt Administrationsrechte\&.
.RE
.PP
\fBblock \fI<MODUL>\fR|\fIall\fR
.RS 4
Verhindert, dass das Modul oder die Module automatisch installiert oder
aktualisiert werden\&.
.P
Bereits installierte Module werden nicht aktualisiert oder gelöscht mit
Ausnahme der Pakete die vom Debian Paketmanagement System verwaltet werden\&.
.P
Benötigt Administrationsrechte\&.
.P
Module die als
.B prerequisite
gekennzeichnet sind können nicht blockiert werden\&.
.RE
.PP
\fBunblock \fI<MODUL>\fR|\fIall\fR
.RS 4
Erlaubt
.B Tomte,
Module die von diesem System benötigt werden automatisch zu installieren oder
zu aktualisieren\&.
.P
Benötigt Administrationsrechte\&.
.RE
.PP
\fBremove \fI<MODUL>\fR
.RS 4
Entfernt das genannte Modul unabhaengig vom gewaehltem Modus
(\fBAUTOMATIC\fR, \fBUPGRADES_ONLY\fR, \fBDONT_CONFIGURE\fR)\&.
.P
Nach Entfernen des Moduls, sollte dieses blockiert werden mit
.RE
.PP
\fBtomte \fBblock \fI<MODUL>\fR
.RS 4
ansonsten wird es wieder automatisch installiert wenn der gewählte Modus
.B AUTOMATIC
ist\&.
.P
Benötigt Administrationsrechte\&.
.P
Im Moment können nur einige Module gelöscht werden\&.
.RE
.PP
.SH "KONFIGURATIONS-MODI"
.RS 4
Benötigt Administrationsrechte\&.
.P
Es gibt drei verschiedene Modi: \fBAUTOMATIC\fR, \fBUPDATES_ONLY\fR und
\fBDONT_CONFIGURE\fR\&.
.P
Diese Modi werden gesetzt über
.IP
\fBsudo tomte \fI<MODUS>\fR
.LP
Der Modus kann ebenfalls manuell über das Erstellen einer leeren Datei mit dem
Namen des gewünschten Modus unter dem Verzeichniss
.BR /etc/tomte/ \&
vorgenommen werden. z.B.
.IP
\fBsudo touch /etc/tomte/AUTOMATIC\fP
.LP
oder
.IP
\fBsudo touch /etc/tomte/UPDATES_ONLY\fP
.LP
oder
.IP
\fBsudo touch /etc/tomte/DONT_CONFIGURE\fP
.LP
.RE
.TP
\fBAUTOMATIC\fR
Dies ist der voreingestellte Modus. Alles wird von
.B Tomte
automatisch installiert/aktualisiert/gelöscht\&.
.RE
.TP
\fBUPDATES_ONLY\fR
Nur die Aktualisierungen werden über
.B Tomte
verarbeitet.
.IP
Keine Module werden ohne Intervention des
Benutzers installiert oder gelöscht\&.
.RE
.TP
\fBDONT_CONFIGURE\fR
Nichts, ausser den Modulen die als
.B prerequisite markiert sind, wird von
.B Tomte
konfiguriert.
.IP
Sinnvoll wenn die Datei z.B. vor der Installation von
.B Tomte
erstellt wird um zu vermeiden, dass
.B Tomte
bei der Installation unerwünschte Änderungen im System
durchführt oder um
.B Tomte
in einem bestimmten Konfigurationszustand einzufrieren\&.
.RE
.PP
.SH "TUXEDO FAI INSTALLATION"
.RS 4
Alles wird automatisch installiert. Nach einer FAI-Installation ist das System
betriebsbereit. Falls neue Module nötig sind, werden diese automatisch
installiert\&.
.RE
.PP
.SH "INSTALLATION AUF VANILLA SYSTEM"
.RS 4
Alles wird automatisch installiert. Wahrscheinlich dauert es ein paar Minuten
bis es fertig ist. Benachrichtigungen werden auf dem Bilschirm angezeigt\&.
.P
Die Installation zu unterbrechen könnte das System zerstören\&.
.P
Falls die Dateien \fBAUTOMATIC\fR, \fBUPDATES_ONLY\fR oder \fBDONT_CONFIGURE\fR unter
/etc/tomte/ erstellt werden, wird
.B Tomte
entsprechend handeln.
.RE
.PP
.SH "INSTALLATION OHNE VERÄNDERUNGEN"
.RS 4
Falls die Datei \fB/etc/tomte/DONT_CONFIGURE\fR erstellt wird und
.B Tomte
danach installiert wird, werden nur die Repositories und Spiegel erstellt (
.B prerequisites
)\&.
.P
Um zu sehen welche Module für das System vorgesehen sind
.IP
      \fBtomte \fBlist\fP
.LP
Um dann ein Modul zu installieren
.IP
      \fBtomte \fBconfigure \fI<MODUL>\fR
.LP
.RE
.PP
.SH "MÖGLICHER ABLAUF"
.RS 4
.B Tomte
installieren, es wird sich um alle Module die vom System benötigt werden
kümmern und es wird ebenfalls den
.B TUXEDO
Kernel installieren, der alle notwendigen Treiber mit liefert\&.
.P
Falls nicht erwünscht ist, dass
.B Tomte
irgend welche Änderungen im System durchführt oder z.B. ein bestimmter Kernel
im System bleiben soll, kann die Datei \fBDONT_CONFIGURE\fR in
.BR /etc/tomte/ \&
erstellt werden.
.B Tomte
wird keine weitere Änderungen im System durchführen, außer den Repositories
und den Debian Pakete Spiegel\&.
Danach könnten die notwendigen Module aufgelistet werden
.IP
      \fBtomte \fBlist\fP
.LP
die Module die nicht erwünscht sind blockieren
.IP
      \fBsudo \fBtomte \fBblock \fI<MODUL>\fP
.LP
und
.B Tomte
in den Modus AUTOMATIC oder UPDATES_ONLY setzen
.IP
      \fBsudo \fBtomte \fBAUTOMATIC\fP
.LP
oder
.IP
      \fBsudo \fBtomte \fBUPDATES_ONLY\fP
.LP
Alternativ können die gewünschten Module manuell installiert werden
.IP
      \fBsudo \fBtomte \fBconfigure \fI<MODUL>\fP
.LP
.RE
.PP
.SH "DATEIEN"
.TP
/etc/tomte/tomte.cfg
Die
.B Tomte
Konfigurationsdateien.
.TP
/var/log/tomte/tomte.log
Die
.B Tomte
Logdatei.
.TP
/etc/tomte/DONT_CONFIGURE
Datei, wenn vorhanden, verhindert dass
.B Tomte
irgendwas konfiguriert außer den notwendigen Modulen (
.B prerequisite
).
.TP
/etc/tomte/UPDATES_ONLY
Bei Vorhandensein werden nur Aktualisierungen durchgeführt.
.TP
/etc/tomte/AUTOMATIC
Bei Vorhandensein lässt
.B Tomte
alle Module und deren Aktualisierungen automatisch durchführen.
