.TH tuxedo-tomte 1
.SH "NAME"
tuxedo-tomte \- Manages fixes for TUXEDO notebooks
.SH "SYNOPSIS"
\fBtuxedo-tomte\fR COMMAND [NAME...]
.SH "DESCRIPTION"
.PP
\fBtuxedo-tomte\fR
is a little helper that provides services, updates and fixes for
TUXEDO devices in the background\&. It does not send any information, telemetry
data or similar stuff out!
.P
Many but not all options require administrator privileges\&.
.SH "COMMANDS"
.PP
The following commands are understood:
.PP 
\fBlist\fR
.RS 4
Lists all available fixes with name, version and whether it is active,
blocked and required for this system\&.
.RE
.PP
\fBdescription \fR\fIMODULE\fR
.RS 4
Shows a small description about the fix\&.
.RE
.PP
\fBconfigure \fIMODULE\fR|\fIall\fR
.RS 4
Configures the specified module or fix if possible\&. That means, it is not
already installed, blocked and designed to fix something on this system\&.
If \fBall\fR is used then all possible fixes will be installed\&.
Does nothing if \fBDONT_CONFIGURE\fR is set\&.
.RE
.PP
\fBreconfigure \fIMODULE\fR|\fIall\fR
.RS 4
Configures the specified module or fix even if it is already installed\&.
It will not do anything if it is blocked or not designed to work on this
system\&.
If \fBall\fR is used then all possible fixes will be reconfigured\&.
Does nothing if \fBDONT_CONFIGURE\fR is set\&.
.RE
.PP
\fBblock \fIMODULE\fR|\fIall\fR
.RS 4
Prevents the module from being installed\&.
Already installed modules will not be upgraded except for packages which are
managed by the systems package manager\&.
Modules marked as
.B prerequisite
can't be blocked\&.
.RE
.PP
\fBunblock \fIMODULE\fR|\fIall\fR
.RS 4
Allows the module to be installed or upgraded if it is required by this system\&.
.RE
.PP
\fBremove \fIMODULE\fR
.RS 4
Removes the named module independent from mode
(AUTOMATIC|UPGRADES_ONLY|DONT_CONFIGURE)\&.
After removing the module it has to be blocked with:
.br
      \fBtomte \fBblock \fIMODULE\fP
.br
or the module will be installed again automatically if the mode is set to
AUTOMATIC\&.
.RE
.PP
.SH "CONFIGURATION MODES"
.RS 4
There are three configuration modes: AUTOMATIC/UPDATES_ONLY/DONT_CONFIGURE.
The modes are set by creating an empty file with the name of the configuration
mode in
.BR /etc/tomte/ \&
The file may be created manually as well\&.
.RE
.TP
\fBAUTOMATIC\fR
This is the default mode. Everything will be installed/updated/removed
automatically by Tomte\&.
.RE
.TP
\fBUPDATES_ONLY\fR
Only updates will be handled automatically by Tomte. No modules will be installed
or removed without user intervention\&.
.RE
.TP
\fBDONT_CONFIGURE\fR
Nothing will be configured by Tomte. Usefull if you want to create the file
before installing Tomte to avoid Tomte to make any unwanted changes to the
system or to set Tomte on hold after having the configuration you want\&.
.RE
.PP
.SH "FAI INSTALLATION"
.RS 4
Everything will be installed automatically. After a FAI installation, the
system should be ready to go. Fixes can be blocked afterwards if e.g. kernel
updates are not desired. If new fixes should be necessary, these will be
installed automatically\&.
.RE
.PP
.SH "INSTALLATION ON VANILLA SYSTEM"
.RS 4
Everything will be installed automatically, it might take a few minutes till
all is installed. Messages will appear on the desktop. Interrupting the
installation might damage the system\&.
.RE
.PP
.SH "INSTALLATION WITHOUT MODIFICATIONS"
.RS 4
If creating the file /etc/tomte/MODE with the
text: 'updates' or 'fixed' inside, Tomte will configure the TUXEDO
repositories and continue as described above\&.
To find out which fixes are available to the system:
.br
      \fBtomte \fBlist\fP
.br

Then to install a required fix:
.br
      \fBtomte \fBconfigure \fIMODULE\fR
