#!/bin/sh
# postinst script for tuxedo-tomte
#
# see: dh_installdeb(1)

#DEBHELPER#

set -e

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
