#!/bin/sh
# postinst script for tuxedo-tomte
#
# see: dh_installdeb(1)

#DEBHELPER#

set -e

case "$1" in
    configure)
		# only run if systemd is active
		if ps --no-headers -o comm 1 | grep 'systemd' > /dev/null; then
			#systemctl start tuxedo-tomte
			systemd-run tuxedo-tomte configure all
			echo "postinst configure ###############################"
		fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
